name: CI

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build app and run tests
      - run: npm ci
      - run: npm run build
      - run: npm test
